server:
  port: 8383
spring:
#  datasource:
#    driver-class-name: org.mariadb.jdbc.Driver
#    password: root
#    url: jdbc:mariadb://localhost:3306/credentialdb
#    username: root
  config:
    import: optional:configserver:http://localhost:8888/
  application:
       name: ApiGateway-microservice 
    
  cloud:
     gateway:
       enabled: true
       routes:
       - id: customer-service
         uri: http://localhost:8181/
         predicates:
         - Path=/customer/**
         
       - id: employee-service
         uri: http://localhost:8183/
         predicates:
         - Path=/employee/**   
    
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      
eureka:
  client: 
      register-with-eureka: true
      service-url:
          defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}
          
logging:
    file:
      name: gateway-log.log
      
management:
  endpoints:
    web:
      exposure:
        include: "*" 